//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Bill_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public int CustomerID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
