//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLabProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sale_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Total { get; set; }
        public int Medicine_id { get; set; }
    
        public virtual Medicine Medicine { get; set; }
    }
}
